baseURL: "https://rishub-tamirisa.github.io/research/"
languageCode: en-us
title: Rishub Tamirisa
enableRobotsTXT: true
taxonomies:
  tag: tags
params:
  description: "I'm an AI researcher currently working on research toward improving both AI capabilities and alignment."
  author: Rishub Tamirisa
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: autumn
